16 routing i login part1
wolox-training/gp-react pull request #20
Opened 2018-11-06 21:02 UTC by gabrielizalo

# Summary

* First task of Routing: Login and using Router to the Game

# Trello Card

https://trello.com/c/uRUucKHu/9-routing-i-login

# Screenshot

<img width="1680" alt="login-1" src="https://user-images.githubusercontent.com/656353/47891069-a944a200-de1f-11e8-8e0b-641083add2db.png">

<img width="1680" alt="login2" src="https://user-images.githubusercontent.com/656353/47891108-c6797080-de1f-11e8-90a3-9005000c0fec.png">

2018-11-07 20:30 UTC, henryzarza requested changes

2018-11-07 20:30 UTC, henryzarza commented on react/react-training/src/app/components/AppRoutes/index.js
> +        <div>
You don't need this `div`

2018-11-07 20:30 UTC, henryzarza commented on react/react-training/src/app/screens/Login/index.js
> +class Login extends Component {
You can change this for `functional` component

2018-11-12 19:24 UTC, wfolini requested changes
Great, Small change!

2018-11-12 19:24 UTC, wfolini commented on react/react-training/src/app/components/AppRoutes/index.js
> +        <Fragment>
Use `Switch` https://reacttraining.com/react-router/core/api/Switch

2018-11-13 20:31 UTC, wfolini approved these changes

2018-11-13 20:40 UTC, henryzarza approved these changes

2018-11-13 20:41 UTC, merged