16: Routing I - Login (Part 2)
wolox-training/gp-react pull request #21
Opened 2018-11-08 21:29 UTC by gabrielizalo

# Summary

* Second task of Routing: Redux form del login

# Trello Card

https://trello.com/c/uRUucKHu/9-routing-i-login

# Screenshot

<img width="1606" alt="16- routing i - login part 2" src="https://user-images.githubusercontent.com/656353/48228513-5c0e8600-e373-11e8-9b23-8041b4e90224.png">

2018-11-13 13:50 UTC, henryzarza requested changes
Very good

2018-11-13 13:50 UTC, henryzarza commented on react/react-training/package.json
> +    "isemail": "^3.2.0",
I think that this dependency isn't necessary, please remove it

2018-11-13 13:50 UTC, henryzarza commented on react/react-training/package.json
> +    "react-router-dom": "^4.3.1"
This isn't `devDependecies` so move it to `dependencies`

2018-11-13 13:50 UTC, henryzarza commented on react/react-training/src/app/components/AppRoutes/index.js
> +        <div>
Change this for [`Switch`](https://reacttraining.com/react-router/core/api/Switch)

2018-11-13 13:50 UTC, henryzarza commented on react/react-training/src/app/screens/Login/components/SignInForm/components/CustomField/index.js
> +const CustomField = props => {
Remember don't create `functional components` as arrow functions

2018-11-13 13:50 UTC, henryzarza commented on react/react-training/src/app/screens/Login/components/SignInForm/components/CustomField/index.js
> +  const { input, type, className, placeholder, meta } = props;
In where is the `proptypes`?

2018-11-13 13:50 UTC, henryzarza commented on react/react-training/src/app/screens/Login/components/SignInForm/components/Validation/index.js
> +import { validateEmail } from '@utils';
I think that this isn't a component, so move it to `utils.js` or `validation.js` file inside of `SignInForm`

2018-11-13 13:50 UTC, henryzarza commented on react/react-training/src/app/screens/Login/components/SignInForm/index.js
> +  handleSubmit: PropTypes.func
This is required

2018-11-13 13:50 UTC, henryzarza commented on react/react-training/src/app/screens/Login/components/SignInForm/index.js
> +class SignInForm extends Component {
A good approach is divide this in `dump` and `smart` component.

2018-11-13 13:50 UTC, henryzarza commented on react/react-training/src/app/screens/Login/components/SignInForm/index.js
> +  form: 'signIn'
This name should be in `constants` file

2018-11-13 13:50 UTC, henryzarza commented on react/react-training/src/app/screens/Login/components/SignInForm/styles.scss
> +}
Add EOF (End Of File)

2018-11-13 13:50 UTC, henryzarza commented on react/react-training/src/app/screens/Login/components/SignInForm/styles.scss
> +  color: $red;
I recommend you change this color or background color because i can't see

2018-11-13 16:54 UTC, gabrielizalo commented
All recommendations are fixed... 👍

2018-11-14 22:27 UTC, henryzarza submitted a review, later dismissed

2018-11-14 22:27 UTC, henryzarza commented on react/react-training/src/app/screens/Login/index.js
> +    return <SignInForm onSubmit={this.handleSubmit} />;
Remember what I said about this component, I do not think this nesting is necessary.

2018-11-14 22:27 UTC, henryzarza commented on react/react-training/src/app/screens/Login/components/SignInForm/layout.js
> +class Layout extends Component {
Change this for `functional component`

2018-11-15 15:52 UTC, gabrielizalo commented
we are readyyyy... 🥇

2018-11-15 19:14 UTC, wfolini approved these changes
Great! apply the comment in the next pr

2018-11-15 19:14 UTC, WFolini commented on react/react-training/src/app/screens/Login/layout.js
> +function Layout(props) {
Apply the destructuring in the function param
```js
function Layout({ handleSubmit }) {
```

2018-11-15 19:19 UTC, merged