19: Redux V - Redux Recompose
wolox-training/gp-react pull request #26
Opened 2018-11-27 20:46 UTC by gabrielizalo

# Summary

* Now Gabo's Tic Tac Toe app is using Redux Recompose.

# Trello Card

https://trello.com/c/MWmkf0nq/17-redux-v-redux-recompose-todo-finger

# Screenshot

<img width="1668" alt="gabo s tic tac toe 2018-11-27 15-43-09" src="https://user-images.githubusercontent.com/656353/49110406-67aae980-f25b-11e8-90c6-8702dc0bc6c0.png">

2018-11-27 23:53 UTC, henryzarza requested changes
Excellent! congratulations only a few comments and we're ready.

2018-11-27 23:53 UTC, henryzarza commented on react/react-training/src/redux/login/actions.js
> +const myActionTypes = ['USER_LOGIN'];
I think that isn't necessary this variable, you can assign directly in the `completeTypes`

2018-11-27 23:53 UTC, henryzarza commented on react/react-training/src/redux/login/actions.js
> +    target: 'userLogin',
To put this value in a constant

2018-11-27 23:53 UTC, henryzarza commented on react/react-training/src/redux/login/actions.js
> +          target: 'userIsLogged',
Move this to constant

2018-11-27 23:53 UTC, henryzarza commented on react/react-training/src/redux/login/actions.js
> +        const userIsLogged = true;
I think that this variable isn't necessary, you can assign this value directly

2018-11-27 23:53 UTC, henryzarza commented on react/react-training/src/redux/login/actions.js
> +        const userSession = response.data.id;
The same here

2018-11-27 23:53 UTC, henryzarza commented on react/react-training/src/redux/user/actions.js
> +const myActionTypes = ['USER_GET', 'USER_PATCH', 'USER_POST'];
The same here, this variable isn't necessary

2018-11-27 23:53 UTC, henryzarza commented on react/react-training/src/redux/user/actions.js
> +    target: 'userData',
Move this to constant variable

2018-11-27 23:53 UTC, henryzarza commented on react/react-training/src/redux/user/actions.js
> +    target: 'userData',
The same here

2018-11-27 23:53 UTC, henryzarza commented on react/react-training/src/redux/user/actions.js
> +    target: 'userData',
And here

2018-11-28 12:31 UTC, wfolini requested changes
Great! Just one comment

2018-11-28 12:31 UTC, WFolini commented on react/react-training/src/constants/index.js
> +export const TARGET_USERLOGIN = 'userLogin';
it isn't necessary to declare this const here if you aren't going to use it in many files. This constants are used only in one file. So, I'd move this three constants to that files

2018-11-28 13:15 UTC, wfolini approved these changes
👌

2018-11-28 14:04 UTC, henryzarza approved these changes

2018-11-28 14:25 UTC, merged