05 content layout
wolox-training/gp-react pull request #7
Opened 2018-10-02 14:44 UTC by gabrielizalo

# Summay

* Updated html and scss files with all cards and the desired layout.

# Trello Card

https://trello.com/c/q2pDyhAT/23-content-layout

# Screenshot

<img width="3046" alt="screenshot 2018-10-02_09-30-29-327" src="https://user-images.githubusercontent.com/656353/46356087-a3448100-c627-11e8-9c12-e3a583838506.png">

<img width="3032" alt="screenshot 2018-10-02_09-30-55-407" src="https://user-images.githubusercontent.com/656353/46356113-ae97ac80-c627-11e8-9ab2-cbae8a292f85.png">

2018-10-02 22:33 UTC, henryzarza requested changes
Good work 👍 , only one correction

2018-10-02 22:33 UTC, henryzarza commented on maquetado/scss/_tech.scss
> +  width: 200px;
I think that the width of the cards could be greater because isn't the same the design

2018-10-03 15:02 UTC, henryzarza approved these changes

2018-10-03 15:17 UTC, mcallegari10 approved these changes

2018-10-03 15:39 UTC, merged